//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MLCadLang.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDD_RUBBERBELT_DIALOG           102
#define CG_IDD_PROGRESS                 103
#define CG_IDS_PROGRESS_CAPTION         104
#define IDB_ARROW_ICON                  104
#define CG_IDR_POPUP_LCLIST_VIEW        105
#define IDD_PROPPAGE4                   106
#define CG_ID_VIEW_LEGOPARTS            107
#define IDR_POPUP_LEGO_CADVIEW          108
#define IDS_PROPSHT_CAPTION             109
#define IDD_PROPPAGE1                   110
#define IDD_PROPPAGE2                   111
#define IDD_PROPPAGE3                   112
#define CG_IDR_POPUP_LCTREE_VIEW        113
#define CG_ID_VIEW_COLORBAR             115
#define CG_IDD_COLORBAR                 116
#define IDS_PROPSHTEXP_CAPTION          118
#define IDD_PROPPAGEEXP1                119
#define IDD_PROPPAGEEXP2                120
#define CG_IDR_POPUP_MAIN_FRAME         122
#define CG_ID_VIEW_NAVIGATEBAR          124
#define IDR_MAINFRAME                   128
#define IDR_LEGOCATYPE                  129
#define IDI_MAILTO                      130
#define IDI_HTTP                        131
#define IDB_RUBBERBELT                  135
#define IDD_DIALOG_COLOR                136
#define IDD_DIALOG_COMMENTS             138
#define IDR_TOOLBAR_ELEMENT             139
#define IDD_DIALOG_PIECES               143
#define IDD_DIALOG_DIMENSIONS           144
#define IDD_DIALOG_NEW_COMMENT          145
#define IDD_DIALOG_SELPART              146
#define IDD_DIALOG_SAVEPIC              148
#define IDD_DIALOG_SEARCHPART           152
#define IDB_BITMAP_STATES               153
#define IDR_TOOLBAR_ADDREM              154
#define IDR_TOOLBAR_SELECT              156
#define IDD_DIALOG_ZOOM                 158
#define IDD_DIALOG_FORM                 159
#define IDD_DIALOG_ROTSTEP              160
#define IDD_DIALOG_NEWSUBPART           162
#define IDD_DIALOG_SELMODEL             163
#define IDD_DIALOG_LISTFORM             165
#define IDD_PROPPAGE5                   166
#define IDR_TOOLBAR_VIEW                166
#define IDD_DIALOG_HELP                 168
#define IDD_DIALOG_FRACT                169
#define IDD_DIALOG_PICMOD               171
#define IDB_BITMAP_LOGO                 179
#define IDD_CUSTCOLOR                   180
#define IDD_DIALOG_BGND                 183
#define IDD_BASEPATH                    184
#define IDD_DIALOG_PRIMITIVE            185
#define IDD_DIALOG_BFC                  186
#define IDI_ICON1                       188
#define IDI_ICON2                       189
#define IDI_ICON3                       190
#define IDI_ICON4                       191
#define IDR_TOOLBAR_EXPERT              192
#define IDR_TOOLBAR_ZOOM                198
#define IDD_DIALOG_BUFEXCHG             200
#define IDD_DIALOG_GRPNAME              202
#define IDD_DIALOG_ENTERPOSMAT          206
#define IDR_TOOLBAR_EDIT                207
#define IDD_PROPPAGE6                   207
#define IDB_BITMAP1                     209
#define IDB_SPRING                      209
#define IDD_DIALOG_MODSEQ               212
#define IDI_ICON_SELUP                  214
#define IDI_ICON_SELDOWN                215
#define IDD_DIALOG_CONFIG_TREE          215
#define CG_IDD_COLORBAR1                216
#define IDD_DIALOG_ROTPT                218
#define IDD_DIALOG_ROTMOD               219
#define IDD_DIALOG_EDITROT              221
#define IDD_AUTOSTEPS                   222
#define IDD_DIALOG_SORTPARMS            223
#define IDD_MINIFIG_CREATOR             224
#define IDI_ICON_MORE_COLORS            226
#define IDR_TOOLBAR_EXTRAS              229
#define IDD_SPRING_GENERATOR            231
#define IDD_HOSE_GENERATOR              232
#define IDD_ARROW_GENERATOR             233
#define IDD_DIALOG_ADDLSYNTH            235
#define IDD_PLATE_GENERATOR             236
#define IDB_BITMAP_PLATE                236
#define IDC_MAILTO                      1000
#define IDC_EDIT1                       1000
#define IDC_BEGINPOINTX                 1000
#define IDC_URL                         1001
#define IDC_EDIT2                       1001
#define IDC_BEGINCONTROLPOINTX          1001
#define IDC_TYPE                        1001
#define IDC_EDIT3                       1002
#define IDC_ENDPOINTX                   1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_EDIT4                       1003
#define IDC_ENCONTROLPOINTX             1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_BEGINPOINTY                 1004
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_BEGINCONTROLPOINTY          1005
#define IDC_LEGO_BASE_PATH              1006
#define IDC_MAIL1                       1006
#define IDC_ENDPOINTY                   1006
#define IDC_COMMENT_LIST                1007
#define IDC_URL1                        1007
#define IDC_EDIT7                       1007
#define IDC_ENCONTROLPOINTY             1007
#define IDC_TRANSPARENT                 1008
#define IDC_EDIT8                       1008
#define IDC_BEGINPOINTZ                 1008
#define IDC_EDIT9                       1009
#define IDC_BEGINCONTROLPOINTZ          1009
#define IDC_ENDPOINTZ                   1010
#define IDC_ENCONTROLPOINTZ             1011
#define IDC_PARTTEXT                    1013
#define IDC_NUMBEROFSTEPS               1014
#define IDC_EDIT10                      1015
#define IDC_FIRSTPARTTEXT               1015
#define IDC_DRAWLINE                    1016
#define IDC_SECTIONS1                   1016
#define IDC_SECTIONS2                   1017
#define IDC_SECTIONS3                   1018
#define IDC_CHECK1                      1019
#define IDC_LENGTH2                     1022
#define IDC_RADIUS                      1024
#define IDC_WIDTH2                      1025
#define IDC_COLORBUT_1                  1064
#define IDC_COLORBUT_2                  1065
#define IDC_COLORBUT_3                  1066
#define IDC_COLORBUT_4                  1067
#define IDC_REP_PARTLIST                1067
#define IDC_COLORBUT_5                  1068
#define IDC_TOTAL_NUM_PIECES            1068
#define IDC_COLORBUT_6                  1069
#define IDC_REPDIM_LIST                 1069
#define IDC_PART_LISTBOX                1069
#define IDC_COLORBUT_7                  1070
#define IDC_EDIT_COMMENT                1070
#define IDC_COLORBUT_8                  1071
#define IDC_COLORBUT_9                  1072
#define IDC_COLORBUT_10                 1073
#define IDC_COLORBUT_11                 1074
#define IDC_SHADING                     1074
#define IDC_COLORBUT_12                 1075
#define IDC_COLORBUT_13                 1076
#define IDC_PRINT_PARTLIST              1076
#define IDC_COLORBUT_14                 1077
#define IDC_PARTS_PER_STEP              1077
#define IDC_COLORBUT_15                 1078
#define IDC_MULTI_STEPS                 1078
#define IDC_COLORBUT_16                 1079
#define IDC_COLORBUT_17                 1080
#define IDC_PRINT_STEPS                 1080
#define IDC_COLORBUT_18                 1081
#define IDC_HIGH_QUALITY                1081
#define IDC_COLORBUT_19                 1082
#define IDC_COLORBUT_20                 1083
#define IDC_COLORBUT_21                 1084
#define IDC_SERIES                      1084
#define IDC_COLORBUT_22                 1085
#define IDC_SNAPSHOT                    1085
#define IDC_COLORBUT_23                 1086
#define IDC_RESOLUTION                  1086
#define IDC_COLORBUT_24                 1087
#define IDC_SHOW_ALL                    1087
#define IDC_COLORBUT_25                 1088
#define IDC_SHOW_OLD_COMMENTS           1088
#define IDC_COLORBUT_26                 1089
#define IDC_XPOS                        1089
#define IDC_COLORBUT_27                 1090
#define IDC_YPOS                        1090
#define IDC_COLORBUT_28                 1091
#define IDC_ZPOS                        1091
#define IDC_COLORBUT_29                 1092
#define IDC_XROT                        1092
#define IDC_COLORBUT_30                 1093
#define IDC_YROT                        1093
#define IDC_COLORBUT_31                 1094
#define IDC_ZROT                        1094
#define IDC_COLORBUT_32                 1095
#define IDC_DRAWTOSELECTION             1095
#define IDC_XSTEP                       1095
#define IDC_COLORBUT_ACT                1096
#define IDC_SAME                        1096
#define IDC_XSTEP2                      1096
#define IDS_STRING_INVNAME              1096
#define IDC_SPEC                        1097
#define IDC_XSTEP3                      1097
#define IDS_ERROR_READINGLF             1097
#define IDC_COLORPICKER                 1098
#define IDS_ERROR_WR_PARTLIST           1098
#define IDC_YSTEP                       1099
#define IDS_ERROR_WR_PARTLIST2          1099
#define IDC_ZSTEP                       1100
#define IDS_ERROR_WR_PARTLIST3          1100
#define IDC_LOOKUP                      1101
#define IDC_YSTEP2                      1101
#define IDS_ERROR_INVFORMULA            1101
#define IDC_SEARCH_NR                   1102
#define IDC_ZSTEP2                      1102
#define IDC_SEARCH_TEXT                 1103
#define IDC_YSTEP3                      1103
#define IDS_STRING_IGNORECH             1103
#define IDC_CASE                        1104
#define IDC_ZSTEP3                      1104
#define IDS_ERROR_NAMEUSED              1104
#define IDS_COLORMORE                   1105
#define IDC_STEPS                       1106
#define IDS_COLORTABLESTORE             1106
#define IDC_SCREEN_SELECTION            1107
#define IDS_REMOVEFAVORITES             1107
#define IDC_ZOOMFACT                    1108
#define IDS_PAGEOFN                     1108
#define IDC_COMBO_GROUP                 1109
#define IDS_ERRORINLINE                 1109
#define IDS_ERRORFILENOTFOUND           1110
#define IDC_VIEW                        1111
#define IDS_FILEEXISTS                  1111
#define IDS_DIMENSIONHEADER             1112
#define IDS_GROUPHEADER                 1113
#define IDS_MODELHEADER                 1114
#define IDS_LISTHEADER                  1115
#define IDC_SCROLL_GROUP                1116
#define IDS_TBNAMES                     1116
#define IDC_SCROLL_PART                 1117
#define IDS_PRNTHEADERLINE              1117
#define IDS_LONGPNTHDLINE               1118
#define IDS_SHORTPNTHDLINE              1119
#define IDS_SELPARTHEADER               1120
#define IDC_PREVIEW                     1121
#define IDS_PLISTHEADER                 1121
#define IDC_PREVIEW_AREA                1122
#define IDS_FILENAMETXT                 1122
#define IDS_ERRORNOMLCADDLL             1123
#define IDS_ERRORINVMLCADDLL            1124
#define IDS_LANGUAGEVERSION             1125
#define IDS_WARNGROUP                   1126
#define IDS_RESET_CONFIG                1127
#define IDS_ERROR_REGAPP                1128
#define IDS_FILEDLG_HEADERS             1129
#define IDS_ELEMDLG_HEADERS             1130
#define IDC_TYPE_REL                    1131
#define IDS_LOAD_DEF_COLOR              1131
#define IDC_TYPE_ABSOLUTE               1132
#define IDC_STEPS2                      1132
#define IDS_ERROR_LSYNTH_CONFIG         1132
#define IDC_TYPE_ADD                    1133
#define IDS_ERROR_LSYNTH_EXECUTE        1133
#define IDC_DEGREE                      1134
#define IDS_ERROR_NOTEMP                1134
#define IDC_PRINT_MODEL                 1135
#define IDC_DEGREE2                     1135
#define IDS_ERROR_RECOVER               1135
#define IDC_NAME                        1136
#define IDC_DEGREE3                     1136
#define IDS_REPORT_FILTER               1136
#define IDC_COMMENT                     1137
#define IDS_MSG_NONEWPARTS              1137
#define IDS_VIEWNAMES                   1138
#define IDC_MODELLIST                   1139
#define IDS_LOAD_STD_COLOR              1139
#define IDC_PARTLIST                    1140
#define IDS_USE_STD_AS_DFLT             1140
#define IDC_ACT_MODEL                   1141
#define IDS_INVALID_LANGUAGE            1141
#define IDS_COLORSORT_HEADER            1142
#define IDC_STATIC_INFOTEXT             1143
#define IDS_RECURSION_ERROR             1143
#define IDC_CUSTOM_PART                 1144
#define IDC_CUST_PARTNAME               1145
#define IDC_LOAD_PART                   1146
#define IDC_PRINT_SUBMODELS             1147
#define IDC_SEPARATE_PL                 1148
#define IDC_PREVIEW_COLOR               1149
#define IDC_BACKGROUND_COLOR            1150
#define IDC_CENTERED                    1151
#define IDC_POSSAME                     1152
#define IDC_SHOW_WARNINGS               1153
#define IDC_SUB_MODELS                  1154
#define IDC_EDITONLOAD                  1155
#define IDC_DEFAULT                     1156
#define IDC_STATIC_MESSAGE              1157
#define IDC_BUTTON_EXIT                 1158
#define IDC_BUTTON_INDEX                1159
#define IDC_BUTTON_CONTENTS             1160
#define IDC_BUTTON_BACK                 1161
#define IDC_BASEPLATE                   1166
#define IDC_BRICK_SIZE                  1168
#define IDC_FPV                         1169
#define IDC_MPV                         1170
#define IDC_USECOLOR                    1171
#define IDC_USEPLATES                   1172
#define IDC_COMPUTE                     1173
#define IDC_FSIZE                       1176
#define IDC_HEIGHT                      1178
#define IDC_SHOW_MODEL                  1179
#define IDC_COLORRANGE                  1180
#define IDC_FILE_NAME                   1181
#define IDC_BROWSE                      1182
#define IDC_PICPV                       1184
#define IDC_MODPV                       1185
#define IDC_COLORMODE                   1190
#define IDC_AUTHOR                      1191
#define IDC_NEWPARTVIEW                 1192
#define IDC_CUSTOM_COLOR                1198
#define IDC_BASEPATH                    1198
#define IDC_COLOR_RANGE                 1199
#define IDC_STATUS                      1200
#define IDC_DEFINE                      1206
#define IDC_COLNUM                      1207
#define IDC_HS1                         1208
#define IDC_V1                          1209
#define IDC_HN1                         1210
#define IDC_HS2                         1211
#define IDC_V2                          1212
#define IDC_SN1                         1213
#define IDC_VN1                         1214
#define IDC_RN1                         1215
#define IDC_GN1                         1216
#define IDC_BN1                         1217
#define IDC_HN2                         1218
#define IDC_SN2                         1219
#define IDC_VN2                         1220
#define IDC_RN2                         1221
#define IDC_GN2                         1222
#define IDC_BN2                         1223
#define IDC_COLORTYPE                   1224
#define IDC_COLORNAME                   1225
#define IDC_DITHERED                    1228
#define IDC_SAVEDEFAULT                 1230
#define IDC_LOADDEFAULT                 1231
#define IDC_CHANGEBP                    1234
#define IDC_XP1                         1235
#define IDC_YP1                         1236
#define IDC_ZP1                         1237
#define IDC_XP2                         1238
#define IDC_VERSIONSTRING               1238
#define IDC_YP2                         1239
#define IDC_ZP2                         1240
#define IDC_CLIP                        1240
#define IDC_XP3                         1241
#define IDC_YP3                         1242
#define IDC_ZP3                         1243
#define IDC_XP4                         1244
#define IDC_SPECIFIED                   1244
#define IDC_YP4                         1245
#define IDC_ZP4                         1246
#define IDC_WINDING                     1246
#define IDC_INVERT_NEXT                 1247
#define IDC_VISIBLETEST                 1248
#define IDC_SKIPSTUDS                   1249
#define IDC_BUFNUMBER                   1251
#define IDC_RETRIEVE                    1252
#define IDC_GROUPNAME                   1254
#define IDC_EXPFORMAT                   1259
#define IDC_EXPMODELS                   1260
#define IDC_STEPS1                      1262
#define IDC_STEPRANGE                   1263
#define IDC_EXPPATH                     1264
#define IDC_EXPPATHBROWSE               1265
#define IDC_EXPIGNROTSTEPS              1266
#define IDC_EXPIGNHIGHLIGHT             1267
#define IDC_AUTOPARTUPGR                1268
#define IDC_L3PPARAS1                   1270
#define IDC_L3PPATH1                    1271
#define IDC_L3PPATH2                    1272
#define IDC_L3PPARAS2                   1273
#define IDC_L3PPATH3                    1274
#define IDC_L3PPARAS3                   1275
#define IDC_BROWSE_LOG                  1276
#define IDC_ENABLEPOSTLOG               1283
#define IDC_POSTLOGPATH                 1284
#define IDC_BROWSE1                     1286
#define IDC_PPENABLE1                   1287
#define IDC_PPISCOMMAND1                1288
#define IDC_BROWSE2                     1289
#define IDC_PPENABLE2                   1290
#define IDC_PPISCOMMAND2                1291
#define IDC_BROWSE3                     1292
#define IDC_PPENABLE3                   1293
#define IDC_PPISCOMMAND3                1294
#define IDC_ROTMAT                      1296
#define IDC_STATTEXT                    1297
#define IDC_SMALLPREV                   1298
#define IDC_PRNTHEADER                  1300
#define IDC_PRNT_FOOTER                 1301
#define IDC_ORIENTMODE_1                1302
#define IDC_ORIENTMODE_2                1303
#define IDC_ALPHA                       1304
#define IDC_ABSOLUTE                    1305
#define IDC_ENTERTYPE                   1306
#define IDC_ENTERTYPE1                  1307
#define IDC_ROTANGLE                    1308
#define IDC_USEPOS                      1309
#define IDC_USEROTVEC                   1310
#define IDC_USEROTMAT                   1311
#define IDC_RESET                       1312
#define IDC_CLEAR                       1313
#define IDC_CONV                        1314
#define IDC_CVTVECMAT                   1315
#define IDC_CVTMATVEC                   1316
#define IDC_REGISTERFILETYPE            1317
#define IDC_3DVIEWACTION_1              1320
#define IDC_3DVIEWACTION_2              1321
#define IDC_FASTSTEPCNT                 1322
#define IDC_MODLIST                     1323
#define IDC_UP                          1324
#define IDC_DOWN                        1325
#define IDC_GROUPS                      1325
#define IDC_ORDER                       1326
#define IDC_RULE                        1328
#define IDC_VIEW_UP                     1329
#define IDC_ORD_UP                      1330
#define IDC_VIEW_DOWN                   1331
#define IDC_ORD_DOWN                    1332
#define IDC_DELETE                      1333
#define IDC_SHOWSTEPNUM                 1334
#define IDC_PRNTSTPNUM                  1335
#define IDC_LANGUAGE                    1337
#define IDC_ORIGIN1                     1338
#define IDC_ORIGIN2                     1339
#define IDC_ORIGIN3                     1340
#define IDC_ORIGIN4                     1341
#define IDC_CUSTPTS                     1342
#define IDC_ADD                         1346
#define IDC_DEL                         1347
#define IDC_SHOWROTPOINT                1350
#define IDC_MODIFY                      1351
#define IDC_ORIGIN5                     1353
#define IDC_FASTRENDER                  1354
#define IDC_IGNORE_COLORS               1355
#define IDC_SAVE_LIST                   1356
#define IDC_USEBFC                      1357
#define IDC_LINEWIDTH                   1361
#define IDC_SUBMODELS                   1362
#define IDC_STATIC_TEXT                 1363
#define IDC_ROTMODEL                    1365
#define IDC_WIDTH                       1366
#define IDC_GRID                        1367
#define IDC_COLOR                       1368
#define IDC_PREVIEW_NOW                 1369
#define IDC_MYSIZE                      1370
#define IDC_PICTYPE                     1371
#define IDC_PERSPECTIVE                 1372
#define IDC_MODE2                       1373
#define IDC_MODE1                       1374
#define IDC_HAT                         1374
#define IDC_NPARTS                      1375
#define IDC_HEAD                        1375
#define IDC_SORTBY1                     1376
#define IDC_NECK                        1376
#define IDC_SORTBY2                     1377
#define IDC_BODY                        1377
#define IDC_SORTBY3                     1378
#define IDC_LEG_LEFT                    1378
#define IDC_ASCENDING                   1379
#define IDC_LEG_RIGHT                   1379
#define IDC_SELECTIONS_ONLY             1380
#define IDC_ACC_LEFT                    1380
#define IDC_ACC_RIGHT                   1381
#define IDC_LEG_ACC                     1382
#define IDC_RIGHT_LEG_ACC               1383
#define IDC_HAT_ANGLE                   1384
#define IDC_HEAD_ANGLE                  1385
#define IDC_RL_ANGLE                    1386
#define IDC_LL_ANGLE                    1387
#define IDC_LHA_ANGLE                   1388
#define IDC_RHA_ANGLE                   1389
#define IDC_LA_ANGLE                    1390
#define IDC_RA_ANGLE                    1391
#define IDC_LH_ANGLE                    1392
#define IDC_RH_ANGLE                    1393
#define IDC_SPIN1                       1394
#define IDC_SPIN2                       1395
#define IDC_SPIN3                       1396
#define IDC_SPIN4                       1397
#define IDC_SPIN5                       1398
#define IDC_SPIN6                       1399
#define IDC_SPIN7                       1400
#define IDC_SPIN8                       1401
#define IDC_SPIN9                       1402
#define IDC_SPIN10                      1403
#define IDC_BODY2                       1404
#define IDC_LH                          1405
#define IDC_RH                          1406
#define IDC_CREATE_MODE1                1407
#define IDC_CREATE_MODE2                1408
#define IDC_CREATE_MODE3                1409
#define IDC_CREATE_MODE4                1410
#define IDC_META_COMMAND                1415
#define IDC_LENGTH                      1416
#define IDC_DISTANCE                    1417
#define IDC_WIDTH2SPIN                  1418
#define IDC_LENGTH2SPIN                 1419
#define IDC_RADIUSSPIN                  1420
#define IDC_DISTANCESPIN                1421
#define IDC_LENGTHSPIN                  1422
#define IDC_WIDTHSPIN                   1423
#define IDC_STATIC_R                    1424
#define IDC_STATIC_L2                   1425
#define IDC_STATIC_S                    1426
#define IDC_POINTERCOL                  1427
#define IDC_INDICOL                     1428
#define IDC_LSYNTH_COMBO                1429
#define IDC_STUDS                       1431
#define IDC_SWAP                        1432
#define IDC_LOAD_STANDARD_COLORS        1433
#define IDC_SORT_TAB                    1434
#define IDC_SAVE_STD_AS_DFLT            1435
#define ID_VIEW_MODEL_TOP               32773
#define ID_VIEW_MODEL_BOTTOM            32774
#define ID_VIEW_MODEL_BELOW             32775
#define ID_VIEW_MODEL_LEFT              32776
#define ID_VIEW_MODEL_RIGHT             32777
#define ID_VIEW_MODEL_FRONT             32778
#define ID_VIEW_MODEL_BACK              32779
#define ID_EDIT_PART_INSERT             32780
#define ID_EDIT_PART_DELETE             32781
#define ID_EDIT_PART_ROTATE             32782
#define ID_EDIT_INSERT_PART             32783
#define ID_EDIT_INSERT_STEP             32784
#define ID_EDIT_INSERT_COMMENT          32785
#define ID_EDIT_INSERT_ROTATION         32786
#define ID_EDIT_INSERT_ROTATIONEND      32787
#define ID_VIEW_MODEL_3D                32788
#define ID_EDIT_MOVE_UX                 32792
#define ID_EDIT_MOVE_DX                 32793
#define ID_EDIT_MOVE_UY                 32794
#define ID_EDIT_MOVE_DY                 32795
#define ID_EDIT_MOVE_UZ                 32796
#define ID_EDIT_MOVE_DZ                 32797
#define ID_VIEW_EDITBAR                 32804
#define ID_VIEW_ELEMENTBAR              32805
#define ID_VIEW_MOVEMENTBAR             32806
#define ID_SETTINGS_CHANGE              32807
#define ID_SETTINGS_EDITMODE            32808
#define ID_EDIT_ROTATE_DX               32816
#define ID_EDIT_ROTATE_UX               32817
#define ID_EDIT_ROTATE_DY               32818
#define ID_EDIT_ROTATE_UY               32819
#define ID_EDIT_ROTATE_DZ               32820
#define ID_EDIT_ROTATE_UZ               32821
#define ID_VIEW_MODEL_WIREGRATING       32828
#define ID_REPORT_PIECES                32829
#define ID_REPORT_DIMENSIONS            32830
#define ID_REPORT_COMMENTS              32831
#define ID_POPUP_FIND                   32846
#define ID_POPUP_ADDTOFAVORITES         32847
#define ID_POPUP_REMOVE                 32848
#define ID_POPUP_FINDAGAIN              32849
#define ID_POPUP_REMOVEALLFAVORITES     32850
#define ID_NAVIGATE_SELTOP              32856
#define ID_NAVIGATE_SELPREV             32857
#define ID_NAVIGATE_SELNEXT             32858
#define ID_NAVIGATE_SELLAST             32859
#define ID_FILE_SAVEPICTURES            32864
#define ID_FILE_SCANPARTS               32865
#define ID_EDIT_VISIBILITY_HIDE         32866
#define ID_EDIT_VISIBILITY_SHOW         32867
#define ID_EDIT_VISIBILITY_SHOWALL      32868
#define ID_FILE_SAVEPARTLIST            32869
#define ID_SETTINGS_DEFAULT             32870
#define ID_MULTIPART_NEWMODEL           32872
#define ID_MULTIPART_SELECTMODEL        32873
#define ID_MULTIPART_IMPORTMODELS       32874
#define ID_MULTIPART_REMOVEMODEL        32875
#define ID_MULTIPART_EXPORTMODELS       32876
#define ID_MULTIPART_CHANGEMODELINFO    32877
#define ID_EDIT_MODIFY                  32878
#define ID_EDIT_PARTCOLOR               32879
#define ID_EDIT_DUPLICATE               32880
#define ID_SETTINGS_GRID_COARSE         32881
#define ID_SETTINGS_GRID_MEDIUM         32882
#define ID_SETTINGS_GRID_FINE           32883
#define ID_VIEW_VIEWBAR                 32884
#define ID_SETTINGS_ZOOM_300            32885
#define ID_SETTINGS_ZOOM_200            32886
#define ID_SETTINGS_ZOOM_150            32887
#define ID_SETTINGS_ZOOM_100            32888
#define ID_SETTINGS_ZOOM_75             32889
#define ID_SETTINGS_ZOOM_50             32890
#define ID_SETTINGS_ZOOM_25             32891
#define ID_SETTINGS_ZOOM_12             32892
#define ID_SETTINGS_ZOOM_6              32893
#define ID_SETTINGS_ZOOM_FIT            32894
#define ID_POPUP_ZOOM_IN                32896
#define ID_POPUP_ZOOM_OUT               32897
#define ID_POPUP_ZOOM_FIT               32898
#define ID_POPUP_ZOOM_SET               32899
#define ID_FILE_SCANMODELS              32910
#define ID_EXTRAS_FRACTALGENERATOR      32911
#define ID_EXTRAS_PICTUREMODEL          32912
#define ID_EXTRAS_HEIGHTMODEL           32913
#define ID_VIEW_COLORBAR                32914
#define ID_VIEW_REFRESH                 32915
#define ID_SETTINGS_MOVEMODE            32916
#define ID_SETTINGS_VIEWMODE            32917
#define ID_FILE_EXPORT                  32919
#define ID_POPUP_OUTLINE                32921
#define ID_SETTINGS_PLACEMODE           32922
#define ID_SETTINGS_ROTATEMODE          32923
#define ID_SETTINGS_SIZEMODE            32926
#define ID_EDIT_ADD_BACKGROUND          32927
#define ID_EDIT_ADD_LINE                32929
#define ID_EDIT_ADD_TRIANGLE            32930
#define ID_EDIT_ADD_QUAD                32931
#define ID_EDIT_ADD_OPTIONALLINE        32932
#define ID_EDIT_ADD_BFCSTATEMENT        32937
#define ID_EDIT_ADD_CLEARSTATEMENT      32939
#define ID_VIEW_TOOLBARS_ZOOMBAR        32940
#define ID_VIEW_TOOLBARS_EXPERTBAR      32941
#define ID_EDIT_ADD_BUFFEREXCHANGE      32943
#define ID_EDIT_GROUP_CREATE            32946
#define ID_EDIT_GROUP_UNGROUP           32947
#define ID_EDIT_GROUP_INFO              32950
#define ID_EDIT_MOVEROT_ENTER           32953
#define ID_EDIT_VISIBILITY_GHOST        32955
#define ID_EDIT_VISIBILITY_GHOSTOFF     32956
#define ID_EDIT_SNAPTOGRID              32962
#define ID_SETTINGS_CENTEREDROTATE      32963
#define ID_VIEW_TOOLBARS_MODIFICATIONBAR 32966
#define ID_SETTINGS_ROTATEGRID          32967
#define ID_NAVIGATE_FASTBACKWARD        32970
#define ID_NAVIGATE_FASTFORWARD         32971
#define ID_MULTIPART_SEQUENCE           32972
#define ID_EXTRAS_UTILITIES_CREATEBMFFILES 32973
#define ID_SETTINGS_GROUPCONFIGURATION  32974
#define ID_SETTINGS_GROUPS_RESET        32975
#define ID_EXTRAS_FILECASH_FLUSH        32976
#define ID_EXTRAS_FILECASH_RESET        32977
#define ID_FILE_REVERT                  32978
#define ID_SETTINGS_DRAWTOSEL           32979
#define ID_POPUP_SELECTALL              32980
#define ID_EDIT_SELECT_SAMEPARTS        32981
#define ID_EDIT_SELECT_SAMECOLOR        32982
#define ID_POPUP_SCROLLBARS             32983
#define ID_EXTRAS_GENERATORS_ROTATIONMODEL 32984
#define ID_EDIT_ADD_AUTOSTEPS           32985
#define ID_EDIT_SORT                    32986
#define ID_EXTRAS_GENERATORS_MINIFIGGENERATOR 32988
#define ID_VIEW_TOOLBARS_EXTRASBAR      32989
#define ID_EXTRAS_GENERATORS_SPRING     32990
#define ID_EXTRAS_GENERATORS_RUBBERBELT 32992
#define ID_EXTRAS_GENERATORS_FLEXIBLEHOSE 32994
#define ID_EXTRAS_GENERATORS_ARROW      32996
#define ID_EXTRAS_LSYNTH_UNGROUP        32999
#define ID_EXTRAS_LSYNTH_HIDEDEFINITION 33000
#define ID_EXTRAS_LSYNTH_HIDESYNTHESIZED 33001
#define ID_EXTRAS_LSYNTH_RUNLSYNTH      33002
#define ID_EXTRAS_LSYNTH_ADDLSYNTHCOMMAND 33003
#define ID_EXTRAS_LSYNTH_HIDENONE       33004
#define ID_EXTRAS_GENERATORS_BASEPLATES 33005
#define ID_VIEW_PANECOORDINATES         33007
#define IDS_STRING_NOHELP               61447
#define IDS_STRING_NOMEM                61448
#define IDS_STRING_MODIFIED             61449
#define IDS_STRING_EXTCHANGEWARN        61452
#define IDS_STRING_CREATEERROR          61453
#define IDS_STRING_READERROR            61454
#define IDS_STRING_MPDRECURSION         61455
#define IDS_STRING_ADDRECURSION         61456
#define IDS_STRING_PASTERECURSION       61458
#define IDS_STRING_NAMEEXISTS           61459
#define IDS_STRING_HASREFS              61460
#define IDS_STRING_FCREATE              61461
#define IDS_STRING_FIO                  61462
#define IDS_STRING_FOPEN                61463
#define IDS_STRING_BMPERROR             61464
#define IDS_STRING_NOPARTLST            61465
#define IDS_STRING_ERRSCANPARTS         61466
#define IDS_STRING_NEWPARTSSAVE         61467
#define IDS_PART_UPGRADE_QUEST          61468
#define IDS_PART_UPGRADE_FAIL           61469
#define IDS_PART_UPGRADE_OK             61470
#define IDS_NOTASSOC                    61471

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         33008
#define _APS_NEXT_CONTROL_VALUE         1435
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
